### ISSUE TITLE
老哥 try/catch 中代码重复，有重复调用关闭连接对象的风险。

### ISSUE THREAD

**Issue by zergmk2** [jackletter/DBUtil#1]
![image](https://user-images.githubusercontent.com/698746/61312201-8251c300-a82a-11e9-9651-13ccef6f6b5c.png)
如上图，finally中和try block中都有close conn的调用，属于重复调用了。
只需要再finally block中写代码就可以了。

**Comment by jackletter** [comment]
是的 代码不够严谨 后面去掉
