### ISSUE TITLE
求助：There is already an open DataReader associated with this Connection which must be closed first.

### ISSUE THREAD

**Issue by merfy** [jackletter/DBUtil#2]
首先感谢您开发的DBUtil，我认为非常有用。

我在使用过程中遇到一个问题，数据库为MySQL，IsKeepConnect为True，有多线程，调用过程中经常会出现错误：“There is already an open DataReader associated with this Connection which must be closed first.”，请问该如何处理？

谢谢！

**Comment by jackletter** [comment]
一个链接只能同时绑定一个打开的datareader，建议转变操作的思路：重新生成一个idb、加锁、取消IsKeeoConnect、写个idb池等

**Comment by merfy** [comment]
非常感谢，我也按照这个思路重新处理了，目前没有这个问题了。
